#!/bin/bash
pushd `dirname ${BASH_SOURCE[0]}` > /dev/null; HERE=`pwd`; popd > /dev/null
cd $HERE

host=127.0.0.1
port=9000

openbrowser() {
  if which open > /dev/null; then
    echo hi
    open http://${host}:${port}
  fi
}

set -e
./install
openbrowser
notingham server --host $host --port $port --data-dir notebooks --site-dir public
